language : cpp
dist: trusty
env:
  - DISPLAY=:99.0
addons:
  apt:
    packages:
    - valgrind
    - jq
compiler:
  - gcc
before_install:
    - export GOPATH=`pwd`/gosrc
    - export PATH=`pwd`/gosrc/bin:$PATH
    - go get qpm.io/qpm
    - sh -e /etc/init.d/xvfb start
script:
    - VERSION=$(jq .version.label qpm.json)
    - VERSION=$(eval echo $VERSION)
    - qpm check
    - if ! head -n 1 asyncfuture.h | grep -q $VERSION; then echo "Version string mismatched"; exit -1 ;fi
    - git clone https://github.com/benlau/qtci.git
    - source qtci/path.env
    - qt-5.7
    - source qt-5.7.env
    - mkdir build
    - cd build
    - run-unittests ../tests/asyncfutureunittests/asyncfutureunittests.pro
    - valgrind --num-callers=30 --leak-check=full --track-origins=yes --gen-suppressions=all --suppressions=asyncfuture.supp ./asyncfutureunittests

